spring.application.name=api

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/api-example
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- H2 (para testes) ---
# spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
spring.h2.console.enabled=true

# --- JWT ---
security.jwt.secret=${SECURITY_JWT_SECRET:Z7QwX9pT4kL1sN8dV3eF2rC6yJ0mA5bG}
security.jwt.expiration=${SECURITY_JWT_EXPIRATION_MILLIS:86400000}

# --- CORS ---
cors.origins=http://localhost:5173

# --- OAuth2 (GitHub) ---
spring.security.oauth2.client.registration.github.client-id=Ov23liCjupJ4bpxmpDr2
spring.security.oauth2.client.registration.github.client-secret=09efa29a2abf1220ab4ad0b7bca94e70b22ed5e9
